<?php

/**
 * @file
 * Contains linxecredit.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function conciliacionadelantos_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the linxecredit module.
    case 'help.page.linxecredit':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This show the code package generated.') . '</p>';
      return $output;

    default:
  }
}
function conciliacionadelantos_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'conciliacionadelantos/conciliacion_adelantos';
}

function conciliacionadelantos_theme() {
  return $theme;
}


